file_format: "1"
id: corne-enc
name: Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - underglow
  - encoder
siblings:
  - corne-enc_left
  - corne-enc_right
